### PR TITLE
修复LoadBalancingDriver.connect对不支持连接的处理逻辑错误

### PR DESCRIPTION
**Pull request by loong95**
这个PR主要是解决了`LoadBalancingDriver.connect`在传入url是其他驱动的连接时没有返回null的问题。同时也把部分`System.out.println`打印的日志修改为用`JUL`输出

### CODE REVIEW

**Comment by lastincisor** [comment]
thank you very match for this pr.
It is recommended to remove [System.out] related code.
debug log Should not appear in base components.

**Comment by loong95** [comment]
> thank you very match for this pr. It is recommended to remove [System.out] related code. debug log Should not appear in base components.

多谢你的建议，我已经移除了调试日志

**Review by lastincisor — APPROVED** [review]
LGTM

**Comment by lastincisor** [comment]
LGTM

**Pull request merged**
